---
- name: minikube server deployment
  hosts: 192.168.1.34
  become: true
  remote_user: kmaster
  tasks:
    - name: Delete Kubernetes resource
      command: kubectl delete -f /home/kmaster/nginx-app/nginx.yaml
      become_user: kmaster
      ignore_errors: yes
    - name: create Kubernetes resource
      command: kubectl apply -f /home/kmaster/nginx-app/nginx.yaml
      become_user: kmaster

